on:
  workflow_dispatch:
  push:

jobs:
  app-inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: VatsalJagani/splunk-app-action@v2
      with:
        splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
        splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}
        app_dir: "sigsci_TA_for_splunk"
